services:
  - type: web
    name: hospital-ssj-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: USER
        sync: false
      - key: PASSWORD
        sync: false
      - key: SERVER
        sync: false
      - key: DATABASE
        sync: false 
      - key: JWT_SECRET
        sync: false